### ISSUE TITLE
autoload not working correctly?

### ISSUE THREAD

**Issue by pimentel** [klmr/vim-snakemake#1]
Hey there,

Thanks for putting this together.

I'm having in issue with this plug-in not loading when I open a Snakefile. If I set the filetype manually to `snakemake` everything looks as expected.

Perhaps adding this to `ftdetect/snakemake.vim` will fix the issue?

```
autocmd BufNewFile,BufRead Snakefile setfiletype snakemake
...
```

Thanks in advance,

Harold

**Comment by klmr** [comment]
Correct, this is an oversight. I’ve changed it, it should work now. Please try it.
